### ISSUE TITLE
Deprecate `RSafeStream`

### ISSUE THREAD

**Issue by stanleyjs** [scottgigante/tasklogger#11]
@scottgigante following up on that PR...

### **Goal:**
I think we can remove `RSafeStream`, or at least come up with a hack that detects if we're inside R.
### **Why:**
It doesn't seem like it's necessary in my testing, and it (may) prevent using stdout/stderr normally inside python, since we're writing everything using `os.write(1,bytes(str,'utf-8))` rather than using the typical stream processing.
### **Questions:**
1) When you say "does logging work inside reticulate?", do you mean "do logs appear in the console?" is there any other way to test this? 
- **If the benchmark is logs appearing in the console, I have shown this in python 3.10 + R 4.04**
2) Does `os.write` actually evade anything we would want to do with streams? 
- Does it make it difficult to use alternative streams, such as files?
- Does it break stream redirection, a la 
```
import io
from contextlib import redirect_stdout

with io.StringIO() as buf, redirect_stdout(buf):
    print('redirected')
    output = buf.getvalue()
```
- If we chop it out, will it get any closer to having better stream handling? 
- - As it stands, it appears that the above `redirect_stdout` snippet does * not *  work with `Logger`, regardless of using `os.write`, so what's the point of removing it ?
3) How the heck does `test_no_stdout` work? What is the expectation?
- I would expect that if you set `sys.stdout=None`, then you're either going to get a `RuntimeError`, or it's going to log to `logging.lastResort`, which by default is a `StreamHandler` on `sys.stderr` at `WARNING`.  If you set `sys.stderr` to `None`, then you should get no output
- - Some scenarios:
```
>>> import sys
>>> import tasklogger
>>> sys.stdout=sys.__stdout__
>>> tasklogger.log_info('hello')
hello
<tasklogger.logger.TaskLogger object at 0x7f4e62b2a620>
```
What's going on here? Let's keep going..
```
>>> sys.stdout=None
>>> tasklogger.log_info('hello')
hello
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: lost sys.stdout
```
With `stdout` gone, we still get `hello` - is the logger falling back to `logging.lastResort`, or is `hello` coming from `os.write`? On the other hand, the interpreter prints the `RuntimeError`, because it can't send the `tasklogger.get_tasklogger().__repr__` to `stdout`.
Now we turn off `stderr`...
```
>>> sys.stdout=None
>>> sys.stderr=None
>>> tasklogger.log_info('hello')
hello
```
This clearly isn't working as intended. Both `stderr` and `stdout` are off,  so we shouldn't get anything - the 'hello' is not coming from calls to `sys.stdout`, it's coming from `os.write`. We've lost our `RuntimeError` for missing `stdout` because `stderr` is gone. 

GIven this walkthrough, my answer to point 2 (does `os.write` break anything) is that yes, it does break things - we get printing to `stdout` even though we've turned off that stream.

**Comment by scottgigante** [comment]
For question 1, we would need to check logging is successfully printed
below a chunk in an RStudio notebook. For question 2, of course I agree, it
would be nice to avoid this if we can. One possibility is to check if there
is anything in os.environ that indicates that we're running inside
reticulate.

**Comment by scottgigante** [comment]
Update on question 1: I just tested this by replacing the call to
`RSafeStream(stream=self.stream)` with `getattr(sys, self.stream)` and it
worked fine in RStudio with notebooks. (obviously this is not a proper
solution, we should parse `self.stream` properly but it worked for testing)

You have my go-ahead to write a PR to remove RSafeStream. Thanks for
looking into this!
