### ISSUE TITLE
Addressing multiple object instances with named logs

### ISSUE THREAD

**Issue by stanleyjs** [scottgigante/tasklogger#5]
Hi,

How do you handle logs that are held in the attributes of a class for which there may be many unique instances? Consider the following pseudocode, which will raise a runtime error when Foo() is instantiated more than once inside a single python session.

```
    class Foo(object):
        def __init__(self,logger = None, verbose=0):
            if logger == None:
                self.logger = tasklogger.TaskLogger(name='Foo',level = verbose)
```

My workaround is this, but I may be missing something in the API that is better.

```
    class Foo(object):
        log_instance = 0
        def __init__(self,logger = None, verbose=0):
            if logger == None:
                Foo.log_instance += 1
                self.logger = tasklogger.TaskLogger(name='Foo ' + str(Foo.log_instance),level = verbose)
```
This just keeps track of how many times `Foo(logger=None) ` has been called

Of course, another way to do this is to use try making the new tasklogger and catch it by calling `get_tasklogger`. But this won't give you unique loggers.

Am I missing something here?

**Comment by stanleyjs** [comment]
Two more caveats:

If you assign `self.logger` to have the name `'Foo ' + str(id(Foo))` this fails when Python reassigns the same address (fun!)

If you are running a development tool that allows you to update code without restarting your python kernel, then the above `Foo.log_instance` workaround will break.

**Comment by scottgigante** [comment]
So to clarify, what you're looking for is for this behaviour:
```
logger1 = tasklogger.get_tasklogger("foo")
logger2 = tasklogger.get_tasklogger("foo")
logger1 == logger2 # True

logger1 = tasklogger.TaskLogger("bar")
logger2 = tasklogger.TaskLogger("bar")
logger1 == logger2 # False
```
At the moment the first section works, the second section throws an exception. Is that right?

**Comment by stanleyjs** [comment]
@scottgigante This is my use, yes. Though it would be nice if tasklogger didn't off the old logger - as there's no way to really tell if that logger is still in use.

It's a little murky and maybe just an API to make the module increment / overwrite / get taskloggers if there is a name collision could work.

May I ask what the inspiration of the name association is, rather than just passing around the logger instance itself? In the case where you're just passing the logger instances around, you have to keep track of them.. but then the naming isn't an issue - for example a class with a logger as an attribute `foo.logger`, could have its own logger instance and not have to worry about name collisions.

**Comment by stanleyjs** [comment]
@scottgigante To be clear, I can certainly see that there is utility in `get_tasklogger`, but I'm not sure where I would use it when I couldn't just pass my desired instance around. Maybe my spaghetti isn't that advanced

**Comment by scottgigante** [comment]
The name association comes from `logging` - they do the same thing there. Would you be happy with a flag that sets the behavior?

* `tasklogger.TaskLogger(if_exists="error")` gives current behaviour (mimics `logging`).
* `tasklogger.TaskLogger(if_exists="increment")` gives a new TaskLogger with the name incremented by an integer
* `tasklogger.TaskLogger(if_exists="ignore")` gives the same TaskLogger (i.e., equivalent to `get_tasklogger`)
