### ISSUE TITLE
Class level API for TaskLogger does not match module level tasklogger api

### ISSUE THREAD

**Issue by stanleyjs** [scottgigante/tasklogger#6]
Hi

This is more of a nitpick, but currently `tasklogger.log_task` is valid, but to do the same thing with an instance `logger = tasklogger.TaskLogger()`, one must call `logger.task`.
Because these APIs are different, one has to parse default module level loggers vs. a class level logger. 

Consider the contrast between these two functions:

```
def foo(logger = None):
     if logger is None:
          #because the APIs dont match, we have to assign each function to a local variable for uniformity
          loginfo = tasklogger.log_info
          logtask = tasklogger.log_task
          .... #etc
    else: #assuming we received a TaskLogger instance
         loginfo = logger.info
         .... #etc

      loginfo('logging')
```

This is way more verbose (in a bad way) than the following, which would only work if the APIs were the same

```
def foo(logger=tasklogger):
     logger.log_info('logging')
```

food for thought

**Comment by scottgigante** [comment]
Sure, this seems like a reasonable change. I'd be happy to deprecate `Tasklogger.foo` in favour of `Tasklogger.log_foo` to make the APIs identical.
